"""Create all tables from ER diagram

Revision ID: fa35777ca3f5
Revises: 
Create Date: 2026-07-23 16:25:08.206482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa35777ca3f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=12), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('active', 'maintenance', 'retired')", name='aircraft_status_valid'),
    sa.CheckConstraint('capacity > 0 AND capacity <= 900', name='aircraft_capacity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_id'), 'aircraft', ['id'], unique=False)
    op.create_index(op.f('ix_aircraft_registration'), 'aircraft', ['registration'], unique=True)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_code'), 'airports', ['code'], unique=True)
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_number')
    )
    op.create_index(op.f('ix_passengers_id'), 'passengers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'user')", name='users_role_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('base_airport_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('captain', 'first_officer', 'cabin_crew')", name='crew_role_valid'),
    sa.CheckConstraint("status IN ('available', 'on_duty', 'rest', 'unavailable')", name='crew_status_valid'),
    sa.ForeignKeyConstraint(['base_airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_base_airport_id'), 'crew', ['base_airport_id'], unique=False)
    op.create_index(op.f('ix_crew_employee_code'), 'crew', ['employee_code'], unique=True)
    op.create_index(op.f('ix_crew_id'), 'crew', ['id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('origin_airport_id', sa.Integer(), nullable=False),
    sa.Column('destination_airport_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gate', sa.String(length=10), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('scheduled','boarding','departed','in_air','landed','delayed','cancelled')", name='flights_status_valid'),
    sa.CheckConstraint('delay_minutes >= 0', name='flights_delay_not_negative'),
    sa.CheckConstraint('origin_airport_id <> destination_airport_id', name='flights_origin_not_destination'),
    sa.CheckConstraint('scheduled_arrival > scheduled_departure', name='flights_arrival_after_departure'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number', 'scheduled_departure', name='flights_number_departure_unique')
    )
    op.create_index(op.f('ix_flights_aircraft_id'), 'flights', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_flights_destination_airport_id'), 'flights', ['destination_airport_id'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_origin_airport_id'), 'flights', ['origin_airport_id'], unique=False)
    op.create_index(op.f('ix_flights_scheduled_departure'), 'flights', ['scheduled_departure'], unique=False)
    op.create_index(op.f('ix_flights_status'), 'flights', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=6), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=4), nullable=True),
    sa.Column('booking_status', sa.String(length=20), nullable=False),
    sa.Column('fare_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('baggage_count', sa.Integer(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("booking_status IN ('confirmed','checked_in','boarded','cancelled','no_show')", name='bookings_status_valid'),
    sa.CheckConstraint('baggage_count >= 0', name='bookings_baggage_not_negative'),
    sa.CheckConstraint('fare_amount >= 0', name='bookings_fare_not_negative'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_number', name='bookings_seat_unique')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_flight_id'), 'bookings', ['flight_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_passenger_id'), 'bookings', ['passenger_id'], unique=False)
    op.create_table('crew_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('role_on_flight', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role_on_flight IN ('captain', 'first_officer', 'cabin_crew')", name='crew_assignments_role_valid'),
    sa.ForeignKeyConstraint(['crew_id'], ['crew.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'crew_id', name='crew_assignments_unique')
    )
    op.create_index(op.f('ix_crew_assignments_crew_id'), 'crew_assignments', ['crew_id'], unique=False)
    op.create_index(op.f('ix_crew_assignments_flight_id'), 'crew_assignments', ['flight_id'], unique=False)
    op.create_index(op.f('ix_crew_assignments_id'), 'crew_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crew_assignments_id'), table_name='crew_assignments')
    op.drop_index(op.f('ix_crew_assignments_flight_id'), table_name='crew_assignments')
    op.drop_index(op.f('ix_crew_assignments_crew_id'), table_name='crew_assignments')
    op.drop_table('crew_assignments')
    op.drop_index(op.f('ix_bookings_passenger_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_flight_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_flights_status'), table_name='flights')
    op.drop_index(op.f('ix_flights_scheduled_departure'), table_name='flights')
    op.drop_index(op.f('ix_flights_origin_airport_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination_airport_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_aircraft_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_crew_id'), table_name='crew')
    op.drop_index(op.f('ix_crew_employee_code'), table_name='crew')
    op.drop_index(op.f('ix_crew_base_airport_id'), table_name='crew')
    op.drop_table('crew')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_passengers_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_aircraft_registration'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_id'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
